### ISSUE TITLE
Move London Councils news work to LGD - what's left to do?

### ISSUE THREAD

**Issue by willguv** [localgovdrupal/localgov_news#17]

**Comment by danchamp** [comment]
At a minimum I'd say:

- [x] Complete work on categories #13 - [PR](https://github.com/localgovdrupal/localgov_news/pull/15)
- [x] Fix coding standards #18 - [PR](https://github.com/localgovdrupal/localgov_news/pull/19)
- [x] Fix #16 (Cache)
- [x] Fix #6 ('Show more' always shows on initial load)
- [ ] Backport styling from London Councils theme [#169](https://github.com/localgovdrupal/localgov_theme/issues/169) - [PR](https://github.com/localgovdrupal/localgov_theme/pull/172)

**Comment by danchamp** [comment]
Superceded by #26
