### ISSUE TITLE
Localgov News - back-end technical audit and fixes

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov_news#29]
Coming from https://trello.com/c/MT7jsnTu

Also see https://github.com/localgovdrupal/localgov_news/issues/26 

This is the more technical audit of the localgov_news module.

What are the criteria by which we accept this into LGD?

- Test coverage?
- Code audit?
- Accessibility?
- JS / Front end approach?

## Expected outputs:

1. Confirmation / recommendations / fixes for the localgov_news
2. A pro-forma process for auditing other new features, defining the checks or gates that we use to assess new features.

## Notes from Dan: 
- [ ] Complete work on categories #13 - [PR](https://github.com/localgovdrupal/localgov_news/pull/15)
- [x] Fix coding standards #18 - [PR](https://github.com/localgovdrupal/localgov_news/pull/19)
- [ ] Fix #16 (Cache)
- [ ] Fix #6 ('Show more' always shows on initial load)
- [ ] Backport styling from London Councils theme [#169](https://github.com/localgovdrupal/localgov_theme/issues/169) - [PR](https://github.com/localgovdrupal/localgov_theme/pull/172)

**Comment by OliverHannan** [comment]
I'll help @danchamp and @markconroy on output 2

**Comment by ekes** [comment]
Question:

As this depends on localgov_core which has an media image entity type what are the requirements for an additional image media entity type here? This to do with it being default?

**Comment by markconroy** [comment]
@ekes I would prefer if we had a default "image" field in localgov_core (not sure if we do) and then use that. It would mean in the new theme, we can have a `node--teaser.html.twig` and set that to render `{{ content.field_image }}` no matter what content type - so news, events, services, etc all share the same generic image field.

I'm not sure if that answers your questions.

**Comment by ekes** [comment]
#30 WSOD get() on null in newsroom if:- newsroom blocks enabled before newsrooms; and newsroom is created before news.

**Comment by ekes** [comment]
So two big questions:-

Newsroom: Has issues #30 #16 and it has been agreed to remove the infinite scrolling. Question then is why isn't it built with views?

Default image: Why a new default image Media Entity Type rather than a category on the existing Image Media Entity Type?
Also why the two fields different image fields, and if this is a good way of doing it, would it be better to offer the pattern in core?

There aren't user stories or requirements yet. So it might be worth making them for these two - at least - and seeing how the solutions fall on balance with them.

**Comment by ekes** [comment]
A separate note I'm going to log here: We do this in localgov_directories as well. `search_api_db` is hard requirement, this makes things work out of the box, and the default configuration has the index on db. But if a site is using a different backend, or wants to switch, is having it as a hard requirement the best way of doing this.

**Comment by ekes** [comment]
> Question then is why isn't it built with views?

It is being rebuilt in views.

> Default image

Switching to a single image field, and to work on a core solution for "default" images.

**Comment by willguv** [comment]
@ekes is there time to rebuild this in views?

**Comment by danchamp** [comment]
@willguv: @markconroy and I did it this morning with input from @ekes and @andybroomfield, I'm updating tests and checking everything over before getting a PR up hopefully later today.

**Comment by willguv** [comment]
@danchamp OK great! Thanks @markconroy and @andybroomfield for helping

**Comment by danchamp** [comment]
Superceded by #31
